---
# tasks file for java

- name: Telechargement de java
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz
    dest: /tmp/jdk-8u181-linux-x64.tar.gz
    headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie; --no-check-certificate'

- name: Extraction de java
  unarchive:
    src: /tmp/jdk-8u181-linux-x64.tar.gz
    dest: /opt
...
